[package]
name = "holo-router-gateway"
edition = "2018"
version = "0.0.0"

[dependencies]
env_logger = "0.6.2"
futures-preview = "0.3.0-alpha.18"
log = "0.4.8"
rustls = "0.16.0"
tokio = "0.2.0-alpha.2"
uuid = { version = "0.7.4", features = ["v4"] }
